posicionamento_partidos = {
    "PT": "Esquerda",
    "PCdoB": "Esquerda",
    "PSOL": "Esquerda",
    "PDT": "Centro-esquerda",
    "PSB": "Centro-esquerda",
    "PV": "Centro-esquerda",
    "REDE": "Centro-esquerda",
    "PSDB": "Centro",
    "PMN": "Centro",
    "PSD": "Centro",
    "PROS": "Centro",
    "AVANTE": "Centro",
    "CIDADANIA": "Centro",
    "SOLIDARIEDADE": "Centro",
    "MDB": "Centro",
    "PL": "Centro-direita",
    "DEM": "Centro-direita",
    "PRTB": "Centro-direita",
    "PMB": "Centro-direita",
    "PODE": "Centro-direita",
    "DC": "Centro-direita",
    "REPUBLICANOS": "Centro-direita",
    "PTB": "Direita",
    "PSC": "Direita",
    "PSL": "Direita",
    "PP": "Direita",
    "PATRI": "Direita",
    "NOVO": "Direita",
    "PATRIOTA": "Direita",
    "UNIÃO": "Direita",



    "S.PART.": "Sem partido",
    
    "PPL": "Esquerda",
    "PST": "Centro-esquerda",
    "SDD": "Centro",
    "SD": "Centro",
    "PMDB": "Centro",
    "PPS": "Centro",
    "PTdoB": "Centro",
    "PTN": "Centro-direita", #? virou Podemos
    "PSDC": "Centro-direita",
    "PTC": "Centro-direita",
    "PRP": "Centro-direita",
    "PMR": "Centro-direita",
    "PRB": "Centro-direita",
    "PFL": "Centro-direita",
    "PHS": "Centro-direita",
    "PPB": "Direita",
    "PRONA": "Direita",
    "PR": "Direita",
    "PAN": "Direita", #? se juntou ao PTB
    "PEN": "Direita",
}
